LIKELION-Android-Bootcamp-4th/lookTalk

lib/ui/common/common_modal.dart, lib/ui/common/const/colors.dart, lib/ui/common/const/gap.dart, lib/ui/main/home/home_screen.dart
- ui 간격 요소 재사용할 수 있도록 gap.dart 파일 생성
- 화면 내 자주 사용하는 SizedBox 대체하여 정상 렌더링 확인
=> Feat: 공통 gap 상수 추가

lib/core/network/dio_client.dart, lib/core/network/endpoints.dart, lib/core/router/router.dart, lib/main.dart, lib/model/client/auth_api_client.dart, lib/model/client/nickname_api_client.dart, lib/model/entity/request/nickname_request.dart, lib/model/entity/request/social_login_request.dart, lib/model/entity/response/nickname_check_response.dart, lib/model/repository/auth_repository.dart, lib/model/repository/nickname_respository.dart, lib/ui/auth/login_screen.dart, lib/ui/auth/seller_info_screen.dart, lib/ui/auth/signup_choice_screen.dart, lib/ui/auth/user_info_screen.dart, lib/ui/common/component/common_text_field.dart, lib/ui/common/const/gap.dart, lib/ui/main/community/community_screen.dart, lib/view_model/auth/auth_view_model.dart, lib/view_model/auth/nickname_check_view_model.dart
- 닉네임 설정 ui는 완료했고 서버 연동 부분하고 있습니다.  
- 애뮬레이터에서 정상 작동하는지 확인했습니다!
=> [WIP] 닉네임 설정 개발 중

lib/core/network/end_points/login_manager/auth_endpoints.dart, lib/core/utils/auth_guard.dart, lib/ui/main/community/community_screen.dart, lib/view_model/auth/auth_view_model.dart
- 로그인 여부 확인해서 화면 분기 구현 완료
- 커뮤니티의 게시글 등록 부분에 화면 분기해둬서 테스트 했습니다!
=> [Feat] 로그인 여부 확인해서 화면 분기 구현 완료

lib/core/network/end_points/login_manager/auth_endpoints.dart, lib/core/network/token_storage.dart, lib/core/router/router.dart, lib/model/client/seller_signup_api_client.dart, lib/model/entity/request/seller_signup_request.dart, lib/model/repository/seller_signup_repository.dart, lib/ui/auth/buyer_info_screen.dart, lib/ui/auth/seller_info_screen.dart, lib/view_model/auth/seller_signup_view_model.dart, lib/view_model/viewmodel_provider.dart
- 판매자 회원가입 서버 연동 완료 
- 애뮬레이터에서 정상 작동하는지 확인했습니다!
=> [Feat] 판매자 회원가입 서버 연동 완료 

android/build/reports/problems/problems-report.html, lib/core/network/end_points/community/community_endpoints.dart, lib/core/network/token_storage.dart, lib/core/router/router.dart, lib/model/client/post_api_client.dart, lib/model/entity/post_entity.dart, lib/model/entity/response/post_response.dart, lib/model/repository/post_repository.dart, lib/ui/main/community/community_entry_point.dart, lib/ui/main/community/post_detail_screen.dart, lib/view_model/community/post_detail_view_model.dart
- 로그인 안된 상태에서 커뮤니티 접근시 무한 로딩 문제 해결했습니다.
- 애뮬레이터에서 정상 작동하는지 테스트 했습니다.
=> [Fix] 로그인 안된 상태에서 커뮤니티 접근시 무한 로딩 문제 해결

lib/core/router/router.dart
- 커뮤니티 My+ 탭 게시판 조회 안되는 에러 수정하였습니다.
-에뮬레이터에서 정상 작동하는지 테스트 해보았습니다!
=> [Fix] 커뮤니티 My+ 탭 게시판 조회 안되는 에러 수정

lib/core/network/dio_client.dart, lib/core/network/end_points/login_manager/auth_endpoints.dart, lib/core/router/router.dart, lib/main.dart, lib/model/client/nickname_api_client.dart, lib/model/entity/comment.dart, lib/model/entity/post_entity.dart, lib/model/entity/request/nickname_request.dart, lib/model/entity/response/comment_response.dart, lib/model/entity/response/nickname_check_response.dart, lib/model/entity/response/post_response.dart, lib/model/repository/nickname_respository.dart, lib/ui/auth/buyer_info_screen.dart, lib/ui/auth/seller_info_screen.dart, lib/ui/common/component/community/comment_item.dart, lib/ui/common/const/gap.dart, lib/ui/main/community/post_detail_screen.dart, lib/view_model/auth/nickname_check_view_model.dart, lib/view_model/auth/seller_signup_view_model.dart, lib/view_model/community/post_detail_view_model.dart, lib/view_model/viewmodel_provider.dart
- 판매자 회원가입시 회사명 중복체크 에러 수정했습니다.
- 에뮬레이터에서 정상 작동 확인했습니다.
=> [Fix] 판매자 회원가입시 회사명 중복체크 에러 수정

lib/ui/main/home/home_screen.dart
- 홈화면 상품클릭 > 상세페이지 연결
- 어떻게 테스트했는지
=> home -product_detail connect

lib/core/network/dio_client.dart, lib/core/network/end_points/mypage.dart, lib/core/router/router.dart, lib/model/entity/response/order_list_response.dart, lib/model/entity/response/order_product_summary.dart, lib/model/repository/order_list_repository.dart, lib/ui/main/category/categorydetail/category_detail_screen.dart, lib/ui/main/home/home_screen.dart, lib/ui/main/mypage/mypage_customer/manage_product/manage_product_screen.dart, lib/ui/main/mypage/mypage_customer/manage_product/manage_widget.dart, lib/ui/main/mypage/mypage_customer/mypage_screen.dart, lib/view_model/category/category_detail/detail_listview_viewmodel.dart, lib/view_model/home/home_category_viewmodel.dart, lib/view_model/mypage_view_model/search_my_product_list_viewmodel.dart, lib/view_model/viewmodel_provider.dart
- 나의 리스트 사용자 주문 목록연동완료 
- 어떻게 테스트했는지
=> 사용자 페이지 연동 완료

lib/core/network/dio_client.dart, lib/model/entity/response/alter_member.dart, lib/model/repository/alter_member_repository.dart, lib/ui/main/mypage/mypage_customer/alter_member.dart, lib/ui/main/mypage/mypage_customer/mypage_screen.dart, lib/view_model/mypage_view_model/alter_member_viewmodel.dart
=> multipart사용

lib/core/router/router.dart, lib/ui/main/mypage/mypage_customer/alter_member.dart, lib/ui/main/mypage/mypage_customer/mypage_screen.dart, lib/view_model/mypage_view_model/alter_member_viewmodel.dart
=> 닉네임 수정 및 마이페이지 데이터 반영안됨 버그 해결 완료

lib/main.dart, lib/model/entity/product_entity.dart, lib/ui/main/mypage/mypage_seller/mypage_screen_product_register.dart, lib/ui/product/product_detail/product_detail_screen.dart, lib/view_model/auth/auth_view_model.dart, lib/view_model/category/category_data_select_viewmodel.dart, lib/view_model/product/product_detail_viewmodel.dart, lib/view_model/product/product_register_viewmodel.dart, lib/view_model/viewmodel_provider.dart
- 어떤 기능을 추가/수정했는지
- 어떻게 테스트했는지
=> 상품 상세페이지 연결 / 판매자 이름뜨게

lib/core/network/end_points/community/community_endpoints.dart, lib/core/router/router.dart, lib/model/client/post_api_client.dart, lib/model/entity/response/post_list_response.dart, lib/model/entity/response/post_response.dart, lib/model/repository/post_repository.dart, lib/ui/common/component/app_bar/app_bar_search_cart.dart, lib/ui/common/component/community/post_item.dart, lib/ui/common/component/community/post_list.dart, lib/ui/main/community/community_my_tab.dart, lib/ui/main/community/community_question_tab.dart, lib/ui/main/community/community_recommend_tab.dart, lib/ui/main/community/post_detail_screen.dart, lib/view_model/community/post_detail_view_model.dart, lib/view_model/viewmodel_provider.dart
- 게시글 삭제 기능 구현 완료했습니다! 
- 애뮬레이터에서 정상 작동하는지 확인했습니다!
=> [Feat] 게시글 삭제 기능 구현 완료

lib/core/router/router.dart, lib/main.dart, lib/model/entity/selected_product.dart, lib/ui/common/component/community/post_list.dart, lib/ui/main/community/communication_product_registration/product_history.dart, lib/ui/main/community/communication_product_registration/product_search.dart, lib/ui/main/community/community_entry_point.dart, lib/ui/main/community/community_my_tab.dart, lib/ui/main/community/community_question_tab.dart, lib/ui/main/community/community_recommend_tab.dart, lib/ui/main/community/post_create_screen.dart, lib/ui/main/community/post_detail_screen.dart, lib/view_model/community/base_post_list_view_model.dart, lib/view_model/community/post_detail_view_model.dart, lib/view_model/community/selected_product_view_model.dart
- 커뮤니티 리스트 중복 호출 되는 문제 해결
- 애뮬레이터에서 정상 동작 확인
=> [Fix] 커뮤니티 리스트 중복 호출 되는 문제 해결

lib/core/network/dio_client.dart, lib/ui/common/component/community/post_item.dart, lib/ui/main/community/post_create_screen.dart
- 커뮤니티 게시글 아이템 클릭 개선
- 애뮬레이터에서 정상 작동 테스트
=> [Fix] 커뮤니티 게시글 아이템 클릭 개선

lib/main.dart, lib/model/repository/wishlist_repository.dart, lib/ui/product/product_detail/product_detail_screen.dart, lib/view_model/wishlist/wishlist_view_model.dart
- 어떤 기능을 추가/수정했는지
- 어떻게 테스트했는지
=> wishlist 연동

lib/ui/main/category/categorydetail/category_detail_screen.dart, lib/ui/main/mypage/mypage_customer/manage_product/manage_product_screen.dart, lib/ui/main/mypage/mypage_customer/mypage_screen.dart, lib/view_model/mypage_view_model/search_my_product_list_viewmodel.dart
=> 카테고리 상세페이지

lib/core/network/dio_client.dart, lib/core/router/router.dart, lib/ui/auth/signup_choice_screen.dart, lib/view_model/auth/auth_view_model.dart
=> [Fix] 회원가입 복구

lib/core/router/router.dart, lib/ui/main/mypage/mypage_seller/mypage_screen_seller.dart, lib/ui/product/product_detail/product_detail_screen.dart
- 어떤 기능을 추가/수정했는지
- 어떻게 테스트했는지
=> 판매자 마이페이지 수정

lib/core/network/dio_client.dart, lib/ui/auth/buyer_info_screen.dart, lib/ui/auth/login_screen.dart, lib/ui/auth/seller_info_screen.dart, lib/ui/cart/order_screen.dart, lib/ui/main/community/post_create_screen.dart, lib/ui/main/mypage/mypage_customer/manage_product/manage_widget.dart, lib/ui/main/mypage/mypage_customer/mypage_screen.dart, lib/ui/main/mypage/mypage_seller/ManageSellerWidget.dart, lib/ui/main/wishlist/wishlist_screen.dart, lib/ui/product/product_detail/product_detail_bottom_sheet.dart, lib/ui/product/review/review_write_screen.dart, lib/view_model/auth/auth_view_model.dart
=> [Fix] 스낵바 수정

lib/model/repository/category_detail_repository.dart, lib/ui/main/home/home_category.dart, lib/ui/main/home/home_screen.dart, lib/view_model/home/home_category_viewmodel.dart, lib/view_model/viewmodel_provider.dart
- 어떤 기능을 추가/수정했는지
- 어떻게 테스트했는지
=> 카테고리 코드 매핑
